version: '3.8'

services:
  backend:
    build: ./backend  
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:80" 
    volumes:
      - ./frontend/src:/app/src 
    depends_on:
      - backend 

